### ISSUE TITLE
is viteplay alive today?

### ISSUE THREAD

**Issue by yoyoys** [hunterliu1003/vibrary#20]
I tried use this template build my own project, and I got many problems.

And I've noticed that viteplay repo is not exist anymore, is that project dead?

**Comment by hunterliu1003** [comment]
@yoyoys 
Sorry for the lately reply.

`viteplay` repo is used privately on my current job, so it's not a public project yet.
Here is the docs of viteplay: https://viteplay.dev/guide/getting-started.html , you can still using it by following the docs
